name: dm-data-unit-uploader
code: dm-data-unit-uploader
version: 2.0.0
category: upload
description: dm-data-unit-uploader plugin
actions:
  upload:
    entrypoint: plugin.upload.UploadAction
    method: job
  download:
    entrypoint: .venv.lib.python3.12.site-packages.synapse_sdk.plugins.testing.sample_actions.DownloadAction
    method: job
  convert:
    entrypoint: .venv.lib.python3.12.site-packages.synapse_sdk.plugins.testing.sample_actions.ConvertAction
    method: job
  train:
    entrypoint: .venv.lib.python3.12.site-packages.synapse_sdk.plugins.testing.sample_actions.TrainAction
    method: job
  add_task_data:
    entrypoint: .venv.lib.python3.12.site-packages.synapse_sdk.plugins.actions.add_task_data.action.AddTaskDataAction
    method: job
