name: dm-data-unit-uploader
code: dm-data-unit-uploader
version: 2.4.1
category: upload
description: dm-data-unit-uploader plugin
supported_data_types:
- image
- video
- text
- pcd
- audio
- data
actions:
  upload:
    entrypoint: plugin.upload.UploadAction
    method: job
  download:
    entrypoint: synapse_sdk.plugins.testing.sample_actions.DownloadAction
    method: job
  convert:
    entrypoint: synapse_sdk.plugins.testing.sample_actions.ConvertAction
    method: job
  train:
    entrypoint: synapse_sdk.plugins.testing.sample_actions.TrainAction
    method: job
  to_task:
    entrypoint: synapse_sdk.plugins.actions.to_task.action.ToTaskAction
    method: job
